definition:
  openapi: "3.1.0"
  info:
    title: "Bookshelf Backend API"
    version: "0.1.0"
    description: "The backend API route descriptions used by Bookshelf"
    license:
      name: "MIT"
      url: "https://spdx.org/licenses/MIT.html"
  servers:
    - url: "http://localhost:3000/"

apis: [./src/swagger.yaml]

components:
  schemas:
    user:
      type: object
      properties:
        _id:
          type: object
        username:
          type: string
        password_hashed:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        last_login:
          type: string
        role:
          type: string
        booklist:
          type: array
      example:
        _id: 67a5c3cba3bb48fa646f9638
        username: User
        password_hashed: $2b$10$Tk179TvlrUQqQuxU/XHoI.rP/edBea12duhNIOTV2VO9FZZhvRo5S
        email: email@email.com
        role: user
        booklist: []
        created_at: 2025-02-07T08:26:51.424Z
        updated_at: 2025-02-07T08:26:51.424Z
        last_login: 2025-02-07T08:26:51.424Z
    book:
      type: object
      properties:
        _id:
          type: object
        title:
          type: string
        author:
          type: string
        release:
          type: string
        genre:
          type: string
        user_id:
          type: object
        description:
          type: string
        added_at:
          type: string
        updated_at:
          type: string
      example:
        _id: 7fdb24bfd2c9eaca400201b8
        title: Lorem
        author: Lorem
        release: 2016-04-08T15:06:21.595Z
        genre: Crime
        user_id: bbcb7eae48aa8ebcf9170140
        description: Lorem
        added_at: 2016-04-08T15:06:21.595Z
        updated_at: 2016-04-08T15:06:21.595Z

  requestBodies:
    user:
      type: object
      required:
        - username
        - password
        - email
        - role
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        role:
          type: string
    book:
      type: object
      required:
        - title
        - author
        - release
        - genre
        - description
      properties:
        title:
          type: string
        author:
          type: string
        release:
          type: string
        genre:
          type: string
        description:
          type: string
    userput:
      type: object
      required:
        - username
        - password
        - email
        - booklist
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        booklist:
          type: array

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

tags:
  - name: login
    description: Login feature
  - name: Users
    description: Routes managing users

paths:
  /api/login:
    post:
      summary: Login for a user
      tags:
        - login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Verification token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        400:
          description: Bad request body
        403:
          description: Invalid username or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: Invalid username or password

  /api/users:
    get:
      summary: Get all users
      tags:
        - Users
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page of pagination (default 0)
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit of requests (default 10)
        - in: query
          name: fields
          description: Comma-separated list of fields to include in the response
          schema:
            type: string
            example: _id,username,role,created_at,updated_at,booklist,last_login
        - in: query
          name: minCreate
          schema:
            type: string
          description: Filter for minimum creation date (ISO string format)
        - in: query
          name: maxCreate
          schema:
            type: string
          description: Filter for maximum creation date (ISO string format)
        - in: query
          name: minUpdate
          schema:
            type: string
          description: Filter for minimum update date (ISO string format)
        - in: query
          name: maxUpdate
          schema:
            type: string
          description: Filter for maximum update date (ISO string format)
        - in: query
          name: username
          schema:
            type: string
          description: Filter for usernames containing the string
        - in: query
          name: email
          schema:
            type: string
          description: Filter for emails containing the string
        - in: query
          name: role
          schema:
            type: string
          description: Filter for role of user
      responses:
        200:
          description: The list of requested users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'

    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/user'
        description: "Required fields of request, roles: user,editor,admin. Authorization required for roles other than user"
      responses:
        201:
          description: The created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: username, password, email, role required || Invalid email format || ${duplicateKey} of value ${duplicateValue} already exists || ValidationError
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
      security:
        - ApiKeyAuth: []

  /api/users/{id}:
    get:
      summary: Get a specific user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - in: query
          name: fields
          description: Comma-separated list of fields to include in the response (if authorized, email and password_hashed can be requested)
          schema:
            type: string
            example: _id,username,created_at,updated_at,last_login,role,booklist
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Data of the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: Invalid fields requested
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid fields requested
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
    put:
      summary: Update a user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/userput'
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Data of the updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ${duplicateKey} of value ${duplicateValue} already exists || Invalid email format || Cannot update ${key} field || Invalid id format || ValidationError
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
    delete:
      summary: Delete a user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: User successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User deleted
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid id format
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
  /api/books:
    get:
      summary: Get all books
      tags:
        - Books
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page of pagination (default 0)
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit of requests (default 10)
        - in: query
          name: fields
          description: Comma-separated list of fields to include in the response
          schema:
            type: string
            example: _id,title,author,release,genre,description,added_at,updated_at
        - in: query
          name: minRelease
          schema:
            type: string
          description: Filter for minimum release date (ISO string format)
        - in: query
          name: maxRelease
          schema:
            type: string
          description: Filter for maximum release date (ISO string format)
        - in: query
          name: title
          schema:
            type: string
          description: Filter for books with titles containing the string
        - in: query
          name: author
          schema:
            type: string
          description: Filter for books with authors containing the string
        - in: query
          name: genre
          schema:
            type: string
          description: Filter for books by genre
        - in: query
          name: user_id
          schema:
            type: string
          description: Filter for books belonging to a specific user
      responses:
        200:
          description: The list of requested books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/book'

    post:
      summary: Create a new book
      tags:
        - Books
      requestBody:
        description: ONLY TITLE IS REQUIRED
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/book'
      responses:
        201:
          description: The created book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: title required|| Invalid date || ValidationError
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
      security:
        - ApiKeyAuth: []

  /api/books/{id}:
    get:
      summary: Get a specific book by id
      tags:
        - Books
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - in: query
          name: fields
          description: Comma-separated list of fields to include in the response
          schema:
            type: string
            example: _id,title,author,release,genre,description,added_at,updated_at
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Data of the book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        400:
          description: Invalid fields requested
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid fields requested
        404:
          description: Book not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Book not found
    put:
      summary: Update a book by id
      tags:
        - Books
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: NOT ALL FIELDS REQUIRED
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/book'
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Data of the updated book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ${duplicateKey} of value ${duplicateValue} already exists || Invalid date format || ValidationError
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        404:
          description: Book not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Book not found
    delete:
      summary: Delete a book by id
      tags:
        - Books
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Book successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Book deleted
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid id format
        404:
          description: Book not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Book not found

security:
  - ApiKeyAuth: []