name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies (both backend and frontend if sharing the same package.json, or run multiple installs as needed)
      - name: Install dependencies
        run: npm install
      
      # Seed the MongoDB database with a .js seed file (adjust path to your seed file)
      - name: Seed Database
        run: node ./path/to/seed.js
      
      # Start the Node.js backend in the background
      - name: Start Node.js Backend
        run: |
          npm run start:backend &
          # Allow some time for the backend to start
          sleep 10

      # Start the Angular frontend in the background
      - name: Start Angular Frontend
        run: |
          npm run start:frontend &
          # Allow some time for the frontend to start
          sleep 10

      # Optional: Wait additional seconds to ensure all services are fully running
      - name: Wait for services to stabilize
        run: sleep 10

      # Run the Cypress tests using the official Cypress GitHub Action
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          # If you have a custom command, make sure it points to your Cypress run command
          command: npm run cy:run
